name: GCP Terraform & Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/primeott/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: rahul-devops@primeott.iam.gserviceaccount.com
    
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
    
      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
    
      - name: Build Image
        run: |
          docker build -t us-central1-docker.pkg.dev/primeott/app-images/your-app:latest .
    
      - name: Push Image
        run: |
          docker push us-central1-docker.pkg.dev/primeott/app-images/your-app:latest
